### Jobless claim CSV files clean and transform

In [1]:
# Dependencies
import os
import pandas as pd

# If exporting to an postgres database
# from sqlalchemy import create_engine
# from config import username, password, dbhost, dbport, dbname

#### Merge eight continued claim and initial claim csv files into one file, beginning by reading in files and creating DataFrames

In [2]:
# Merge eight continuing and initial claim csv files to one file for jobless claims

# Create variable names to make pd.read_csv simpler
file1 = '2018_cont_idwd_data_417.csv'
file2 = '2018_initial_idwd_data_834.csv'
file3 = '2019_cont_idwd_data_672.csv'
file4 = '2019_initial_idwd_data_2.csv'
file5 = '2020_cont_idwd_data_380.csv'
file6 = '2020_init_idwd_data_26.csv'
file7 = '2021partial_cont_idwd_data_784.csv'
file8 = '2021partial_initial_idwd_data_76.csv'

In [3]:
# Create a dataframe using file1
file1_path = os.path.join('.', 'assets', 'Jobless Claims', file1)
file1_df = pd.read_csv(file1_path, low_memory=False)

In [4]:
# file1_df
# Viewing data, identified 4 rows at top plus rows with NaN values at bottom to clean

# Read in again, skipping unneeded rows at top 
file1_path = os.path.join('.', 'assets', 'Jobless Claims', file1)
file1_df = pd.read_csv(file1_path, low_memory=False, skiprows=4)
file1_df.head()

,Geography,State Fips,County Fips,Year,Month,Month Code,week,Continued Claims,Pct. Change from Same~br~Week Last Year
0,"Marion County, IN",18.0,97.0,2018.0,January,1.0,1.0,"3,133",-26.10%
1,"Marion County, IN",18.0,97.0,2018.0,January,1.0,2.0,"3,238",-26.90%
2,"Marion County, IN",18.0,97.0,2018.0,January,1.0,3.0,"3,290",-27.60%
3,"Marion County, IN",18.0,97.0,2018.0,January,1.0,4.0,"3,323",-28.00%
4,"Marion County, IN",18.0,97.0,2018.0,February,2.0,5.0,"3,360",-27.30%

In [5]:
# Create the other dataframes skipping unneeded top rows 
file2_path = os.path.join('.', 'assets', 'Jobless Claims', file2)
file2_df = pd.read_csv(file2_path, low_memory=False, skiprows=4)

file3_path = os.path.join('.', 'assets', 'Jobless Claims', file3)
file3_df = pd.read_csv(file3_path, low_memory=False, skiprows=4)

file4_path = os.path.join('.', 'assets', 'Jobless Claims', file4)
file4_df = pd.read_csv(file4_path, low_memory=False, skiprows=4)

file5_path = os.path.join('.', 'assets', 'Jobless Claims', file5)
file5_df = pd.read_csv(file5_path, low_memory=False, skiprows=4)

file6_path = os.path.join('.', 'assets', 'Jobless Claims', file6)
file6_df = pd.read_csv(file6_path, low_memory=False, skiprows=4)

# 2021 Data, through end of June 2021
file7_path = os.path.join('.', 'assets', 'Jobless Claims', file7)
file7_df = pd.read_csv(file7_path, low_memory=False, skiprows=4)

# 2021 Data, through end of June 2021
file8_path = os.path.join('.', 'assets', 'Jobless Claims', file8)
file8_df = pd.read_csv(file8_path, low_memory=False, skiprows=4)

#### Begin clean up of dataframes, removing NaN rows and performing other clean up as needed

In [6]:
# Drop the rows at end of chart with NaN results, leaving 52 rows (weeks) for the year
file1_df = file1_df.dropna(axis="rows", how="any")
file1_df.tail()

,Geography,State Fips,County Fips,Year,Month,Month Code,week,Continued Claims,Pct. Change from Same~br~Week Last Year
47,"Marion County, IN",18.0,97.0,2018.0,December,12.0,48.0,"2,239",-12.00%
48,"Marion County, IN",18.0,97.0,2018.0,December,12.0,49.0,"2,287",-12.50%
49,"Marion County, IN",18.0,97.0,2018.0,December,12.0,50.0,"2,442",-11.50%
50,"Marion County, IN",18.0,97.0,2018.0,December,12.0,51.0,"2,389",-12.20%
51,"Marion County, IN",18.0,97.0,2018.0,December,12.0,52.0,"2,539",-14.70%

In [7]:
# Drop the rows at end of chart with NaN results for remaining dataframes
file2_df = file2_df.dropna(axis="rows", how="any")
file3_df = file3_df.dropna(axis="rows", how="any")
file4_df = file4_df.dropna(axis="rows", how="any")
file5_df = file5_df.dropna(axis="rows", how="any")
file6_df = file6_df.dropna(axis="rows", how="any")
file7_df = file7_df.dropna(axis="rows", how="any")
file8_df = file8_df.dropna(axis="rows", how="any")

In [8]:
# Unusual July entry at end of file8 (2021 continued claims ends with last week of June)
file8_df.tail()

,Geography,State Fips,County Fips,Year,Month,Month Code,week,Initial Claims,Pct. Change from Same~br~Week Last Year
22,"Marion County, IN",18.0,97.0,2021.0,June,6.0,23.0,"1,270",-72.70%
23,"Marion County, IN",18.0,97.0,2021.0,June,6.0,24.0,"1,311",-75.30%
24,"Marion County, IN",18.0,97.0,2021.0,June,6.0,25.0,"1,410",-78.30%
25,"Marion County, IN",18.0,97.0,2021.0,June,6.0,26.0,"1,451",-86.90%
26,"Marion County, IN",18.0,97.0,2021.0,July,7.0,27.0,"1,282",-72.30%

In [9]:
# Permanently remove the July row for the 2021 data
clean_file8_df= file8_df.drop(file8_df.tail(1).index)
clean_file8_df.tail()

,Geography,State Fips,County Fips,Year,Month,Month Code,week,Initial Claims,Pct. Change from Same~br~Week Last Year
21,"Marion County, IN",18.0,97.0,2021.0,May,5.0,22.0,"1,476",-67.70%
22,"Marion County, IN",18.0,97.0,2021.0,June,6.0,23.0,"1,270",-72.70%
23,"Marion County, IN",18.0,97.0,2021.0,June,6.0,24.0,"1,311",-75.30%
24,"Marion County, IN",18.0,97.0,2021.0,June,6.0,25.0,"1,410",-78.30%
25,"Marion County, IN",18.0,97.0,2021.0,June,6.0,26.0,"1,451",-86.90%

#### Create one DataFrame by merging and appending

In [10]:
# Merge file1 with file 2, with initial and continued claims in same row
merge_files1_2_df = pd.merge(file1_df, file2_df, on=["Geography", "State Fips", "County Fips", "Year", 
                                                     "Month", "Month Code", "week"], how='left')
merge_files1_2_df.head()

,Geography,State Fips,County Fips,Year,Month,Month Code,week,Continued Claims,Pct. Change from Same~br~Week Last Year_x,Initial Claims,Pct. Change from Same~br~Week Last Year_y
0,"Marion County, IN",18.0,97.0,2018.0,January,1.0,1.0,"3,133",-26.10%,739.0,-7.00%
1,"Marion County, IN",18.0,97.0,2018.0,January,1.0,2.0,"3,238",-26.90%,781.0,-0.50%
2,"Marion County, IN",18.0,97.0,2018.0,January,1.0,3.0,"3,290",-27.60%,539.0,-15.30%
3,"Marion County, IN",18.0,97.0,2018.0,January,1.0,4.0,"3,323",-28.00%,540.0,-12.30%
4,"Marion County, IN",18.0,97.0,2018.0,February,2.0,5.0,"3,360",-27.30%,470.0,-14.10%

In [11]:
# Merge the remainder of the data same way (each file will contain the initial and continuous for that year)
merge_files3_4_df = pd.merge(file3_df, file4_df, on=["Geography", "State Fips", "County Fips", "Year", 
                                                     "Month", "Month Code", "week"], how='left')
merge_files5_6_df = pd.merge(file5_df, file6_df, on=["Geography", "State Fips", "County Fips", "Year", 
                                                     "Month", "Month Code", "week"], how='left')
merge_files7_8_df = pd.merge(file7_df, clean_file8_df, on=["Geography", "State Fips", "County Fips", "Year", 
                                                           "Month", "Month Code", "week"], how='left')
merge_files7_8_df.head()

,Geography,State Fips,County Fips,Year,Month,Month Code,week,Continued Claims,Pct. Change from Same~br~Week Last Year_x,Initial Claims,Pct. Change from Same~br~Week Last Year_y
0,"Marion County, IN",18.0,97.0,2021.0,January,1.0,1.0,"13,084",360.90%,"2,313",410.60%
1,"Marion County, IN",18.0,97.0,2021.0,January,1.0,2.0,"13,267",360.70%,"15,914",2592.70%
2,"Marion County, IN",18.0,97.0,2021.0,January,1.0,3.0,"13,084",347.30%,"4,063",768.20%
3,"Marion County, IN",18.0,97.0,2021.0,January,1.0,4.0,"9,896",236.90%,"3,653",769.80%
4,"Marion County, IN",18.0,97.0,2021.0,January,1.0,5.0,"9,159",198.90%,"4,371",950.70%

In [12]:
# Append all years into one dataframe
append_claims_years_df = merge_files1_2_df.append([merge_files3_4_df, merge_files5_6_df, merge_files7_8_df])
append_claims_years_df

,Geography,State Fips,County Fips,Year,Month,Month Code,week,Continued Claims,Pct. Change from Same~br~Week Last Year_x,Initial Claims,Pct. Change from Same~br~Week Last Year_y
0,"Marion County, IN",18.0,97.0,2018.0,January,1.0,1.0,"3,133",-26.10%,739,-7.00%
1,"Marion County, IN",18.0,97.0,2018.0,January,1.0,2.0,"3,238",-26.90%,781,-0.50%
2,"Marion County, IN",18.0,97.0,2018.0,January,1.0,3.0,"3,290",-27.60%,539,-15.30%
3,"Marion County, IN",18.0,97.0,2018.0,January,1.0,4.0,"3,323",-28.00%,540,-12.30%
4,"Marion County, IN",18.0,97.0,2018.0,February,2.0,5.0,"3,360",-27.30%,470,-14.10%
...,...,...,...,...,...,...,...,...,...,...,...
21,"Marion County, IN",18.0,97.0,2021.0,May,5.0,22.0,"7,208",-79.60%,"1,476",-67.70%
22,"Marion County, IN",18.0,97.0,2021.0,June,6.0,23.0,"6,871",-80.60%,"1,270",-72.70%
23,"Marion County, IN",18.0,97.0,2021.0,June,6.0,24.0,"6,472",-81.70%,"1,311",-75.30%
24,"Marion County, IN",18.0,97.0,2021.0,June,6.0,25.0,"6,028",-82.70%,"1,410",-78.30%
25,"Marion County, IN",18.0,97.0,2021.0,June,6.0,26.0,"8,453",-75.80%,"1,451",-86.90%

#### Perform addtional clean up on the merged DataFrame

In [13]:
# Clean dataframe to only include columns of interest, and rename columns
cleaned_claims_df = append_claims_years_df[['Year', 'Month', 'Month Code', 'week', "Continued Claims", 
                                   'Pct. Change from Same~br~Week Last Year_x', 'Initial Claims', 
                                   'Pct. Change from Same~br~Week Last Year_y']].copy()
cleaned_claims_df = cleaned_claims_df.rename(columns={"Year" : "year", 
                                                      "Month" : "month",
                                                      "Month Code":"month_code",
                                                      "Continued Claims": "continued_claims", 
                                                      "Pct. Change from Same~br~Week Last Year_x":"cont_pct_change_same_wk_last_year", 
                                                      "Initial Claims":"init_claims",
                                                      "Pct. Change from Same~br~Week Last Year_y":"init_pct_change_same_wk_last_year"
                                             })
cleaned_claims_df

,year,month,month_code,week,continued_claims,cont_pct_change_same_wk_last_year,init_claims,init_pct_change_same_wk_last_year
0,2018.0,January,1.0,1.0,"3,133",-26.10%,739,-7.00%
1,2018.0,January,1.0,2.0,"3,238",-26.90%,781,-0.50%
2,2018.0,January,1.0,3.0,"3,290",-27.60%,539,-15.30%
3,2018.0,January,1.0,4.0,"3,323",-28.00%,540,-12.30%
4,2018.0,February,2.0,5.0,"3,360",-27.30%,470,-14.10%
...,...,...,...,...,...,...,...,...
21,2021.0,May,5.0,22.0,"7,208",-79.60%,"1,476",-67.70%
22,2021.0,June,6.0,23.0,"6,871",-80.60%,"1,270",-72.70%
23,2021.0,June,6.0,24.0,"6,472",-81.70%,"1,311",-75.30%
24,2021.0,June,6.0,25.0,"6,028",-82.70%,"1,410",-78.30%
25,2021.0,June,6.0,26.0,"8,453",-75.80%,"1,451",-86.90%

In [14]:
# Update year column to integer
year_label = cleaned_claims_df['year'].astype(int)
cleaned_claims_df['year_'] = year_label

In [15]:
# Converting continued claims from string to integer
cleaned_claims_df['continued_claims'] = cleaned_claims_df['continued_claims'].str.replace(',', '')
cleaned_claims_df['continued_claims'] = cleaned_claims_df['continued_claims'].astype(int)
cleaned_claims_df

,year,month,month_code,week,continued_claims,cont_pct_change_same_wk_last_year,init_claims,init_pct_change_same_wk_last_year,year_
0,2018.0,January,1.0,1.0,3133,-26.10%,739,-7.00%,2018
1,2018.0,January,1.0,2.0,3238,-26.90%,781,-0.50%,2018
2,2018.0,January,1.0,3.0,3290,-27.60%,539,-15.30%,2018
3,2018.0,January,1.0,4.0,3323,-28.00%,540,-12.30%,2018
4,2018.0,February,2.0,5.0,3360,-27.30%,470,-14.10%,2018
...,...,...,...,...,...,...,...,...,...
21,2021.0,May,5.0,22.0,7208,-79.60%,"1,476",-67.70%,2021
22,2021.0,June,6.0,23.0,6871,-80.60%,"1,270",-72.70%,2021
23,2021.0,June,6.0,24.0,6472,-81.70%,"1,311",-75.30%,2021
24,2021.0,June,6.0,25.0,6028,-82.70%,"1,410",-78.30%,2021
25,2021.0,June,6.0,26.0,8453,-75.80%,"1,451",-86.90%,2021

In [16]:
cleaned_claims_df['init_claims'] = cleaned_claims_df['init_claims'].astype(str)
cleaned_claims_df['init_claims'] = cleaned_claims_df['init_claims'].str.replace(',', '')
cleaned_claims_df['init_claims'] = cleaned_claims_df['init_claims'].astype(float)
#cleaned_claims_df['init_claims'] = cleaned_claims_df['init_claims'].str.replace('.0', '')
cleaned_claims_df

,year,month,month_code,week,continued_claims,cont_pct_change_same_wk_last_year,init_claims,init_pct_change_same_wk_last_year,year_
0,2018.0,January,1.0,1.0,3133,-26.10%,739.0,-7.00%,2018
1,2018.0,January,1.0,2.0,3238,-26.90%,781.0,-0.50%,2018
2,2018.0,January,1.0,3.0,3290,-27.60%,539.0,-15.30%,2018
3,2018.0,January,1.0,4.0,3323,-28.00%,540.0,-12.30%,2018
4,2018.0,February,2.0,5.0,3360,-27.30%,470.0,-14.10%,2018
...,...,...,...,...,...,...,...,...,...
21,2021.0,May,5.0,22.0,7208,-79.60%,1476.0,-67.70%,2021
22,2021.0,June,6.0,23.0,6871,-80.60%,1270.0,-72.70%,2021
23,2021.0,June,6.0,24.0,6472,-81.70%,1311.0,-75.30%,2021
24,2021.0,June,6.0,25.0,6028,-82.70%,1410.0,-78.30%,2021
25,2021.0,June,6.0,26.0,8453,-75.80%,1451.0,-86.90%,2021

In [18]:
cleaned_claims_df['init_claims'] = cleaned_claims_df['init_claims'].fillna(0)

In [19]:
cleaned_claims_df['init_claims'] = cleaned_claims_df['init_claims'].astype(int)
cleaned_claims_df

,year,month,month_code,week,continued_claims,cont_pct_change_same_wk_last_year,init_claims,init_pct_change_same_wk_last_year,year_
0,2018.0,January,1.0,1.0,3133,-26.10%,739,-7.00%,2018
1,2018.0,January,1.0,2.0,3238,-26.90%,781,-0.50%,2018
2,2018.0,January,1.0,3.0,3290,-27.60%,539,-15.30%,2018
3,2018.0,January,1.0,4.0,3323,-28.00%,540,-12.30%,2018
4,2018.0,February,2.0,5.0,3360,-27.30%,470,-14.10%,2018
...,...,...,...,...,...,...,...,...,...
21,2021.0,May,5.0,22.0,7208,-79.60%,1476,-67.70%,2021
22,2021.0,June,6.0,23.0,6871,-80.60%,1270,-72.70%,2021
23,2021.0,June,6.0,24.0,6472,-81.70%,1311,-75.30%,2021
24,2021.0,June,6.0,25.0,6028,-82.70%,1410,-78.30%,2021
25,2021.0,June,6.0,26.0,8453,-75.80%,1451,-86.90%,2021

In [ ]:
filtered1_df = cleaned_claims_df[cleaned_claims_df['init_claims'].str.contains(',', na=False)]


#filtered1_df['continued_claims'] = filtered1_df['continued_claims'].str.replace(',', '')
#cleaned_claims_df['init_claims'] = cleaned_claims_df['init_claims'].astype(int)
#https://stackoverflow.com/questions/59756961/select-rows-from-pandas-dataframe-where-a-specific-column-contains-numbers
#filtered1_df = cleaned_claims_df['init_claims'].str.contains(",")
#filtered1_df = filtered1_df.dropna(axis="rows", how="any")
#filter[like='739']
#df[df[‘column’].str.contains(‘,’, na=False)]

# Part of the column is float and part is string - would like all to INT when it goes to csv

In [ ]:
filtered1_df['init_claims'] = filtered1_df['init_claims'].str.replace(',', '')
filtered1_df

In [ ]:
filtered2_df = cleaned_claims_df                         
         #df[pd.to_numeric(df.SIC, errors='coerce').notnull()]                        
                                 
filtered2_df

In [ ]:
cleaned_claims_df = cleaned_claims_df[['year_', 'month', 'month_code', 'week', 
                        'continued_claims', 'cont_pct_change_same_wk_last_year',
                        'init_claims', 'init_pct_change_same_wk_last_year']]
cleaned_df = cleaned_claims_df.rename(columns = {'year_' : 'year'}, inplace =False)
cleaned_df

In [ ]:
# Reset index# Replace any NaN with 0 (one visible in 2020)
final_claims_df = cleaned_df.reset_index(inplace=False)
final_claims_df

In [ ]:
# Remove the extra index column that was numbered 1-52 for each year
del final_claims_df['index']

In [ ]:
# Add a column to include year and month
year_label2 = final_claims_df['year'].astype(str)
final_claims_df['timeframe'] = year_label2 + " " + final_claims_df['month']
final_claims_df = final_claims_df[['year', 'month', 'timeframe', 'month_code', 'week', 
                        'continued_claims', 'cont_pct_change_same_wk_last_year',
                        'init_claims', 'init_pct_change_same_wk_last_year']]
final_claims_df

For exporting file to a postgres database

In [ ]:
# Export to an existing postgres db, if desired (add a config.py file that includes the credentials)
# connection_string = f'postgresql://{username}:{password}@{dbhost}:{dbport}/{dbname}'

# engine = create_engine(connection_string)
# conn = engine.connect()

In [ ]:
# final_claims_df.to_sql(name='claims', con=conn, if_exists='replace')

#### For exporting file to csv

In [ ]:
# Export file to csv
final_claims_path = os.path.join('.', 'assets', 'Jobless Claims', 'unempl_claims.csv')
final_claims_df.to_csv(final_claims_path, header=True)

### Summary: Jobless claim CSV files clean and transform

1. Read in all 8 of the files (2018 to 2021, initial claims and continued claims)
2. Cleaned excess rows at top and bottom of the dataframes
3. Cleaned a July 2021 week for initial claims from the data (week was not included in continued claims) 
4. Merged the continued and initial claims dataframes for each year together
5. Appended all the years together into one dataframe
7. Cleaned the dataframe for columns not needed and renamed others
8. Updated year column to data type integer, and added a column to display year and month
9. Updated continued claims column to integer (from string with commas)
10. Reset the index for continuous numbering